## To use this config file rather than config.py, move it to ~/.cache/disco/ and rename it params.yaml
# (replace "/" with "\" if using Windows). See the GitHub wiki for more information.

## General ##

# Name of each class mapped to its numeric id. Zero-based indexing (Begin at 0 and count up).
# Note that you can have multiple names for each code.
name_to_class_code: {"A": 0, "B": 1, "BACKGROUND": 2, "X": 2}
# Mapping from numeric id to label. Zero-based indexing (Begin at 0 and count up).
class_code_to_name: {0: "A", 1: "B", 2: "BACKGROUND"}

## Visualization ##

# Colors used for each class for visualization.
name_to_rgb_code: {"A": "#B65B47", "B": "#A36DE9", "BACKGROUND": "#AAAAAA"}
# number of ffts for visualization.
visualization_n_fft: 1150
# How many columns to show in the visualization. Increasing this allows you to see more (squeezed) of the spectrogram.
visualization_columns: 1000

## Data Extraction ##

# Any csv labels to exclude in data extraction (and therefore training)
excluded_classes: ("Y", "C")

## Inference: Hidden Markov Model ##

# Transition matrix for the Hidden Markov Model.
# Indexing across rows and columns should correspond to the numerical order (indexing) in name_to_index.
hmm_transition_probabilities: [
  [0.995, 0.00000, 0.005],
  [0.0000, 0.995, 0.005],
  [0.00001, 0.00049, 0.9995],
]
# Start probabilities for the Hidden Markov Model.
hmm_start_probabilities: [0, 0, 1]
# Emission probabilities for the Hidden Markov Model. Rows follow zero-based indexing and correspond to name_to_index.
hmm_emission_probabilities: [
  {0: 0.995, 1: 0.00005, 2: 0.00495},
  {0: 0.1, 1: 0.88, 2: 0.020},
  {0: 0.05, 1: 0.05, 2: 0.9},
]

## Inference: General ##
aws_download_link: "https://beetles-cnn-models.s3.amazonaws.com/model_{}.pt"


## Labeling ##

# How many rows to remove from the spectrogram. In effect, this is a high pass square-wave filter.
vertical_cut: 20
# Custom key mapping from keyboard key to label. Capital letters are accepted.
key_to_label: {"y": "A", "w": "B", "e": "BACKGROUND"}


## Training / Advanced Settings ##

# torchaudio.Spectrogram default number of bins.
default_spectrogram_num_rows: 128
# What character to interpret as a mask flag in training
mask_flag: -1